### ISSUE TITLE
Port upper air support from MetPy

### ISSUE THREAD

**Issue by dopplershift** [Unidata/siphon#130]
Remote server access should be the purview of Siphon, not MetPy, so we should move the upper air code (that reads from Wyoming and Iowa St.) here.

**Comment by jrleeman** [comment]
We need to make sure this is bumped to the next release per the MetPy depreciation warning.

**Comment by dopplershift** [comment]
Punting from 0.5 to next release so we can resolve:
1. Need to either port metpy's CDM layer or re-write using netCDF4-python in-memory support. I lean to the latter, but at that point we should probably just rely upon netCDF4.
1. Need to figure out the package layout for this, especially with an eye towards adding additional services like these, such as AWS/S3-based REST services

**Comment by dopplershift** [comment]
Closed by #147.
