### ISSUE TITLE
Add GitHub files

### ISSUE THREAD

**Issue by dopplershift** [Unidata/siphon#141]
- CODEOWNERS: While we don't have any real concept of owners, it might be nice to automatically get review requests
- SUPPORT: Note our various support channels

These are open for discussion.

**Comment by jrleeman** [comment]
With @lesserwhirls, you, and myself as global owners?

**Comment by dopplershift** [comment]
Yup.

**Comment by jrleeman** [comment]
I'll add em' post 🍔
