### ISSUE TITLE
Siphon default regex in siphon/catalog.py fails for days 30/31

### ISSUE THREAD

**Issue by pjpokran** [Unidata/siphon#172]
Siphon routine filter_time_nearest was returning the wrong times for days 30 and 31 of a month. I believe the problem is line 44 of siphon/catalog.py. The default regular expression is currently 

    default_regex = re.compile(r'(?P<year>\d{4})(?P<month>[01]\d)(?P<day>[012]\d)_'
                               r'(?P<hour>[012]\d)(?P<minute>[0-5]\d)')

which only accounts for days 01 through 29. To include days 30 and 31, you need to add a 3 to the day part:

    default_regex = re.compile(r'(?P<year>\d{4})(?P<month>[01]\d)(?P<day>[0123]\d)_'
                               r'(?P<hour>[012]\d)(?P<minute>[0-5]\d)')

Working on a pull request with the fix.
Cheers. Pete

**Comment by dopplershift** [comment]
Well that was silly.

**Comment by pjpokran** [comment]
Happy Friday to you :) time for a :beer:

**Comment by dopplershift** [comment]
Closed by #173 .
