### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/siphon#175]
I would like to suggest that we change the license from MIT to [BSD-3](https://opensource.org/licenses/BSD-3-Clause). This would make our python project licenses the same (i.e. [MetPy](https://raw.githubusercontent.com/Unidata/MetPy/master/LICENSE)). It would also be in line with other Unidata projects. Comments welcome!

**Comment by jrleeman** [comment]
Given that there's been no discussion, are we clear to do this for the next release?

**Comment by lesserwhirls** [comment]
+1

**Comment by dopplershift** [comment]
Go for it.

**Comment by lesserwhirls** [comment]
![dance](https://m.popkey.co/d216f9/l6JM0_f-maxage-0.gif)
