### ISSUE TITLE
Move iastate upper air from MetPy

### ISSUE THREAD

**Issue by jrleeman** [Unidata/siphon#190]
The upper air data support in MetPy goes away in the upcoming release (0.8) and we need to have the Iowa archive code moved here before then so folks can continue to use it.

**Comment by dopplershift** [comment]
Duplicate of #156 .

**Comment by jrleeman** [comment]
Ha - I searched for this and Iowa doesn't return anything... Yay for filing more verbose issues so we can find them I suppose.
