### ISSUE TITLE
Add unit helper for pandas data frames

### ISSUE THREAD

**Issue by jrleeman** [Unidata/siphon#203]
I propose a helper that goes through the columns of a pandas data frame and returns a dict with the keys being column names and the values being united arrays. Of course this would only work on our data frames with a `.units` attribute, but it would reduce boiler plate in places.

**Comment by dopplershift** [comment]
You could pass in the units as a dictionary. Default it to `None`, and if not passed see if the data frame has a `units` attribute.

**Comment by jrleeman** [comment]
Closing in favor of this living in MetPy instead. See https://github.com/Unidata/MetPy/issues/797
