### ISSUE TITLE
IGRA2 bugs

### ISSUE THREAD

**Issue by swnesbitt** [Unidata/siphon#212]
I use IGRA data for research and am excited to see this in `siphon`.

I did some cross checking and it seems like the code is not reading the data correctly.

Looking at the following raw data:
```
#ARM00087344 1983 07 02 12 9999   15 usaf-ds3          -313167  -642167
21 -9999  94800B  484   108B-9999    28 -9999 -8888 
10 -9999  85000  1395B  138B-9999    80   280   134 
10 -9999  70000  3000B   36B-9999    70   195    56 
10 -9999  50000  5650B -137B-9999   140   190    56 
10 -9999  40000  7310B -245B-9999   150   210   190 
10 -9999  30000  9340B -401B-9999    90   225   216 
10 -9999  25000 10550B -485B-9999 -9999   255   247 
22 -9999  22870 11129B -526B-9999 -9999 -9999 -9999 
20 -9999  20800 11751B-9999 -9999 -9999   250   175 
10 -9999  20000 12000B -529B-9999 -9999   250   175 
10 -9999  15000 13850B -537B-9999 -9999   285   309 
20 -9999  13100 14698B-9999 -9999 -9999   295   680 
10 -9999  10000 16410B -615B-9999 -9999   295   680 
10 -9999   7000 18630B -601B-9999 -9999   260   257 
10 -9999   5000 20760B -565B-9999 -9999   280   180 
```
the last two columns in the sounding are wind speed and wind direction.  In this sounding, the lowest level is missing.

When I read the code in `siphon` 0.7, I get the following for u and v wind:
```
date = datetime(1983,7,2,12)
station = 'ARM00087344'
df, header = IGRAUpperAir.request_data(date, station)
print(list(zip(df['u_wind'],df['v_wind'])))
[(-26.7, -9999.9), (1.1, -7.4), (-11.5, -0.2), (-3.6, 5.1), (6.9, 2.9), (-9999.9, 7.1), (-9999.9, -5.2), (-9999.9, -9999.9), (-9999.9, 7.2), (-9999.9, 12.4), (-9999.9, -16.4), (-9999.9, -3.6), (-9999.9, -9999.9)]
```
I am expecting missing values to line up with only 2 missing wind levels.

If you want to see my code for reading IGRA V2 data (i dump to netCDF), it is here:
https://gist.github.com/swnesbitt/b79389e9998b21e800b6ac67dac3f4bd

**Comment by dopplershift** [comment]
@DanielWatkins Any thoughts here?

**Comment by DanielWatkins** [comment]
Hmmm. I'm not sure why those numbers are coming up for you. The results I get are right, at least in most fields (the -999.9's in `relative_humidity` were supposed to be `NaN`'s, so I'll have to fix that.)

````
from datetime import datetime
from siphon.simplewebservice.igra2 import IGRAUpperAir
date = datetime(1983,7,2,12)
station = 'ARM00087344'
df, header = IGRAUpperAir.request_data(date, station)

df.loc[:,['pressure','height','relative_humidity','u_wind','v_wind']]
````
index  | pressure | height | relative_humidity | u_wind | v_wind 
-- | -- | -- | -- | -- | --
0 | 948.0 | 484 | -999.9 | NaN | NaN
1 |  850.0 | 1395 | -999.9 | 13.2 | -2.3
2 | 700.0 | 3000 | -999.9 | 1.4 | 5.4
3 | 500.0 | 5650 | -999.9 | 1.0 | 5.5
4 | 400.0 | 7310 | -999.9 | 9.5 | 16.5
5 | 300.0 | 9340 | -999.9 | 15.3 | 15.3
6 |  250.0 | 10550 | -999.9 | 23.9 | 6.4
7 |  228.7 | 11129 | -999.9 | NaN | NaN
8 |  208.0 | 11751 | -999.9 | 16.4 | 6.0
9 |  200.0 | 12000 | -999.9 | 16.4 | 6.0
10 | 150.0 | 13850 | -999.9 | 29.8 | -8.0
11 | 131.0 | 14698 | -999.9 | 61.6 | -28.7
12 |  100.0 | 16410 | -999.9 | 61.6 | -28.7
13 | 70.0 | 18630 | -999.9 | 25.3 | 4.5
14 | 50.0 | 20760 | -999.9 | 17.7 | -3.1

Are you seeing the same issue with other dates? Does it happen with the derived as well as the standard data?

Unrelated question, would you prefer there be an option to return the raw error codes (-9999 and -8888) or does the current approach of replacing those with `NaN` work?

**Comment by swnesbitt** [comment]
Finally got back to this.

This seems to be working fine on a linux machine, just not on MacOS.  I will try to make my environment the same and see if this is a dependency issue.

I think that some users might appreciate to have the codes -8888 and -9999 preserved, although I just use the `Nan` values myself.

**Comment by jrleeman** [comment]
@swnesbitt - Keep us posted and we're happy to help troubleshoot. I don't foresee us adding the capability to preserve the missing data codes as it's not a very Pythonic interface and `NaN`s are really the right solution.

**Comment by dopplershift** [comment]
@swnesbitt That's weird. It works for me fine on MacOS; Python 3.6 from conda-forge and running in JupyterLab.

**Comment by DanielWatkins** [comment]
@swnesbitt Glad it's at least working for you on Linux. It's been working on my Mac. When/if the same error rears its head again, could you share the full returned dataframe?

**Comment by swnesbitt** [comment]
did a conda update --all and the problem is resolved on MacOS.
