### ISSUE TITLE
Some missing values not being converted to NaN in IGRA2

### ISSUE THREAD

**Issue by DanielWatkins** [Unidata/siphon#213]
Values flagged as missing or invalid in the raw IGRA2 files contain the value -9999 or -8888. On fields that have a decimal value (e.g. 1234 representing 123.4) instead of NaN we sometimes get -999.9.

**Comment by DanielWatkins** [comment]
@avatar101 Glad you found the code! `igratools` is an old incomplete version of what's in Siphon. The version in Siphon is much simpler than the approach I was taking in `igratools`. For one thing, I learned about the existence of `pandas.read_fwf()` which was helpful and faster.

**Comment by avatar101** [comment]
I'm also using pd.read_fwf() but, your overall approach is much better. If you're interested in the approach I'm using, it is based on this https://stackoverflow.com/questions/48992164/reading-file-between-headers-in-python

It makes the code shorter but, I find it a bit complicated. I find your approach better and certainly, your function is much more versatile and powerful than what I could come up with. However, I still need some time to go through all the code you wrote.

**Comment by dopplershift** [comment]
@DanielWatkins did your PR #219 fix this?
