### ISSUE TITLE
(IGRA) Feature to provide information on the number of soundings for a given day and their launch hour

### ISSUE THREAD

**Issue by avatar101** [Unidata/siphon#218]
My biggest hurdle while going through the IGRA data is that different stations have different sounding hours. The most general is probably the 00 or 12 UTC but many stations also have soundings at odd times.  For eg,
station id UKM00003026 has 3 soundings on 31 Dec 1997 at 5, 11 and 23 UTC. As of now, the data can be only imported if the launching hours on a particular date is known beforehand.
Hence, I request for a way to check the sounding hours of a particular data while trying to import the data. 

What I tried in the function I wrote for reading IGRA data is to just print all the data for a given day and thus get an idea of the sounding time. It's not the prettiest approach but something along the lines of returning all the launch hours for a given date from the headers would be nice.

Thanks,

**Comment by DanielWatkins** [comment]
As the function is set up now, all you need to do is set a time range and it will pull all the sounding from that day. So for your example, you could write 
````
date_begin = datetime(1997,12,31,0)
date_end = datetime(1997,12,31,23)
station = 'UKM00003026'
df, header = IGRAUpperAir.request_data([date_begin, date_end], station)
````
The resulting dataframe would have all three of those soundings:

````
print(df.date.unique())

['1997-12-31T05:00:00.000000000' '1997-12-31T11:00:00.000000000'
 '1997-12-31T17:00:00.000000000' '1997-12-31T23:00:00.000000000']
````
You could then either use groupby if you have a function you want to apply to each date, or you could just do something like
````
df.loc[df.date.dt.hour == 5,:]
````
if you want to look at an individual sounding.

The length of the dataframe `header` tells you the number of records retrieved, as well as telling you how many levels are reported in each sounding.

````
header.loc[:,['date','number_levels','latitude','longitude']]

````
 date | number_levels | latitude | longitude
 -- | -- | -- | --
1997-12-31 05:00:00 | 94 | 58.217 | -6.317
1997-12-31 11:00:00 | 90 | 58.217 | -6.317
1997-12-31 17:00:00 | 66 | 58.217 | -6.317
1997-12-31 23:00:00 | 99 | 58.217 | -6.317

**Comment by avatar101** [comment]
Thanks, that's really helpful.
