### ISSUE TITLE
Calucated relative humidity overestimating by a tens in IGRA derived

### ISSUE THREAD

**Issue by avatar101** [Unidata/siphon#221]
@DanielWatkins Hi, the IGRA-2 derived is missing division by 10 in "calculated relative humidity" and is thus, overestimating the value by a tens extra.

I've checked with the following raw data and for a couple of other stations as well.

> #RSM00023022 1998 01 06 12 9999   27    214 80600  1739    42-99999-99999-99999-99999 98258   278-99999-99999-99999-99999    32    15   -13    34-99999-99999
 102100      55      55    2497     -28    2482      69    2497    2482     756     929  -99999     813    -354       0    -208     -30    -153     322
 100100  -99999     199    2493       0    2492      91    2493    2492     683     896  -99999     762       0     -30       0     -52       0     316
 100000     210     206    2493      52    2493     145    2493    2493     683     896  -99999     762     -93     -30    -109     -52     -44     315
  97400  -99999     403    2503     -91    2521      10    2503    2522     728     979  -99999     744      15  -99999  -99999  -99999  -99999     306
  94800  -99999     600    2485     144    2523     244    2485    2523     623     834  -99999     747     -11  -99999  -99999  -99999  -99999     300
  92500     780     780    2511     167    2567     292    2511    2568     783    1051  -99999     745     333     -92     -74     -77     -63     291
  92200  -99999     804    2515      20    2574     122    2515    2574     819    1088  -99999     753    -279  -99999  -99999  -99999  -99999     289
  85000    1400    1404    2527      30    2647     135    2527    2647     709    1208  -99999     587       8    -138     -22    -116     -17     265
  80600  -99999    1794    2539     -64    2700      37    2539    2701     790    1339  -99999     590     -18  -99999  -99999  -99999  -99999     251
  70000    2830    2828    2473     -63    2738      39    2473    2739     427     748  -99999     571     107    -169      31    -141       6     222
  62900  -99999    3596    2425     -57    2768      48    2425    2769     313     479  -99999     653    -184  -99999  -99999  -99999  -99999     203
  53000  -99999    4794    2357     -74    2825      27    2357    2826     106     246  -99999     432      96    -109       7    -130      59     175
  50000    5200    5193    2327     -58    2836      50    2327    2836      85     181  -99999     471     -21    -106      21    -106     -16     167
  40000    6690    6691    2241     -60    2911      50    2241    2911      31      71  -99999     440     -20     -75      35    -130       5     139
  38200  -99999    6991    2223     -27    2926      96    2223    2926      25      58  -99999     434     -10  -99999  -99999  -99999  -99999     134
  30000    8550    8548    2181     -41    3076      82    2181    3076      15      35  -99999     418     -16     -10      23    -120     -46     107
  28000  -99999    8988    2163      -8    3112     130    2163    3112      12      28  -99999     411      -2       0     -36    -140     -11     101
  25800  -99999    9505    2159      20    3179     171    2159    3179      11      27  -99999     410       5  -99999  -99999  -99999  -99999      93
  25000    9710    9704    2163      -4    3214     143    2163    3214      12      28  -99999     411     -38     -26      18    -148       6      90
  20000   11120   11120    2157     -10    3416     145    2157    3416       9      26  -99999     358      -4       0       7    -140       1      72
  15000   12930   12928    2139     -28    3678     120    2139    3678       7      21  -99999     351     -12      12      14    -139      12      54
  13700  -99999   13495    2123     -22    3746     138    2123    3747       6      17  -99999     344      -9  -99999  -99999  -99999  -99999      50
  10700  -99999   15018    2089     -14    3956     156    2089    3956       4      11  -99999     331      -5      41       7    -113     -21      40
  10000   15440   15431    2083     -11    4022     169    2083    4022       3      10  -99999     329      -5      44      34    -122     -25      37
   9120  -99999   16001    2077     -15    4117     171    2077    4117       3       9  -99999     326      -6      63     -31    -136      36      34
   7000   17600   17599    2053      -7    4390     200    2053    4390       2       7  -99999     317      -3      14       3     -79       8      26
   5540  -99999   19002    2043  -99999    4670  -99999    2043    4670       2       6  -99999     313  -99999      18  -99999     -68  -99999      21

`
df_d_23022, header_d_23022 = IGRAUpperAir.request_data(datetime(1998,1,6,12), 'RSM00023022', derived=True )`

**Comment by DanielWatkins** [comment]
Thanks for finding it. That's an easy fix - as is, it just imported the number in the raw data, I forgot to include the converter for that column. Same thing with reported relative humidity.

**Comment by avatar101** [comment]
Yes, true that. So, would it be fixed in the new release or can I just copy the code file for IGRA from the repo and replace it with the older version?

**Comment by DanielWatkins** [comment]
I'll put in a pull request, it should be in the next version. In the meantime, you can still use the version in the code, just add a processing step. Something like:
`df.loc[:,'relative_humidity'] = df.loc[:,'relative_humidity']/10`

**Comment by DanielWatkins** [comment]
@avatar101 can you close this issue? The fix has been merged into the main branch.

**Comment by dopplershift** [comment]
Fixed by #223.
