### ISSUE TITLE
IGRA-2 - bug in flagging missing dewpoint values

### ISSUE THREAD

**Issue by swnesbitt** [Unidata/siphon#226]
I believe that `dewpoint_depression` needs to be added to this list within the igra service @DanielWatkins 

```
df = df.dropna(subset=('temperature', 'reported_relative_humidity',
                                   'u_wind', 'v_wind'), how='all').reset_index(drop=True)
```
I will create a pull request.

**Comment by swnesbitt** [comment]
Addressed in PR #227

**Comment by dopplershift** [comment]
Nice catch!

**Comment by DanielWatkins** [comment]
Since PR 227 fixed this, I think that this issue can be closed.
