### ISSUE TITLE
Upper air data from the University of Wyoming using station number

### ISSUE THREAD

**Issue by ctroupin** [Unidata/siphon#240]
Hi,

The [WyomingUpperAir](https://github.com/Unidata/siphon/blob/master/siphon/simplewebservice/wyoming.py#L20) class works fine when one uses the station identifier, unfortunately some stations (Europe, Africa, ...) are not assigned such an ID, though they have a station number.

What about extending the method [_get_data_raw](https://github.com/Unidata/siphon/blob/master/siphon/simplewebservice/wyoming.py#L121) to allow for a station number?

**Comment by jrleeman** [comment]
Hi @ctroupin - this class does actually accept station number. Are you passing it as a string? 

There was an issue #238 of failure when some of the metadata were missing which was fixed by PR #239 and will be in the next siphon release. Is that the issue you were seeing?

**Comment by ctroupin** [comment]
Yes, I'm calling the method with a string
```python
date = datetime(2018, 6, 25, 12)        
station = "60018"    
df = WyomingUpperAir.request_data(date, station)
```
(the date seems available, otherwise I get another error message), this leads to

```
~/Software/PythonEnvs/Unidata/local/lib/python3.6/site-packages/siphon/simplewebservice/wyoming.py in _get_data(self, time, site_id)
     83         lines = meta_data.splitlines()
     84         station = lines[1].split(':')[1].strip()
---> 85         station_number = int(lines[2].split(':')[1].strip())
     86         sounding_time = datetime.strptime(lines[3].split(':')[1].strip(), '%y%m%d/%H%M')
     87         latitude = float(lines[4].split(':')[1].strip())

ValueError: invalid literal for int() with base 10: '180625/1200'
```
so yes you're right, the issue is the same as #238 (missing metadata).

Thanks!

**Comment by jrleeman** [comment]
No problem! We are planning on cutting a new release of siphon in mid-august, so it will be conda installable then or you can run master. Sorry for the issue!
