### ISSUE TITLE
Improve IGRA2 date range error

### ISSUE THREAD

**Issue by dopplershift** [Unidata/siphon#316]
When there are no data available for a particular date range from IGRA2, it would be very helpful to the users to include the range of data that is actually found in the file. This will require actually calculating the min/max date, but we are already scanning through all of them so it shouldn't be too much more effort.

**Comment by DanielWatkins** [comment]
This could be done via a scan of the file "igra2-station-list.txt", which is in the IGRA2 FTP ftp://ftp.ncdc.noaa.gov/pub/data/igra/

It would be helpful in general to have a utility for grabbing the station information based on some kind of filter, like saying "Fetch me a list of all the stations in the country / latlon box / state".
