### ISSUE TITLE
Importing siphon.catalog messes up logging

### ISSUE THREAD

**Issue by hcholm** [Unidata/siphon#317]
`catalog.py` configures logging on import, overriding any logging config set up by the client.

This line should be removed:

```python
logging.basicConfig(level=logging.ERROR) 
```

I haven't looked for similar cases in other parts of the code.

**Comment by hcholm** [comment]
I see that `logging.basicConfig` is being called in a lot of imports. A workaround example:

```python
import logging
from siphon.catalog import Dataset, TDSCatalog
from siphon.ncss import NCSS
import importlib
importlib.reload(logging)
```

**Comment by joleenf** [comment]
Hi, I ran into this issue as well recently.  
``` python
import logging
from siphon.catalog import TDSCatalog

FORMAT = '%(asctime)s %(clientip)-15s %(user)-8s %(message)s'
logging.basicConfig(format=FORMAT)
logger = logging.getLogger(__name__)
logger.warning("Test This")
```

Will not work when TDSCatalog is imported.  It confused me for a while because I was convinced I had forgotten how to use the logger.
