### ISSUE TITLE
Fix error in IGRA2-Derived wind column

### ISSUE THREAD

**Issue by DanielWatkins** [Unidata/siphon#320]
Pretty simple, and I'm hoping I can get it fixed in the next few days. I noticed that the wind values are utterly wrong in the retrieved IGRA2-Derived files, and looking closer it's due to me leaving out the column "relative_humidity_gradient" when defining the dataframe. So all the values listed as u_wind are actually relative_humidity_gradient.

**Comment by dopplershift** [comment]
Fixed by #321 .
