### ISSUE TITLE
Improve example testing process

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/siphon#39]
Examples solely showing siphon functionality can be pretty boring, but combining those examples with a pretty picture can help quite a bit.

Unfortunately, this tends to introduce non-siphon related dependencies. While matplotlib is not a big deal, as is it pip installable, Cartopy is a big deal and at this point cannot be used on Travis using our current notebook testing infrastructure. At some point we need to revisit the example testing process to see if we can enable our examples to use cartopy.

Also, examples could probably use vcrpy to eliminate network traffic and reliance of our examples on a server being up and running 24x7.

**Comment by dopplershift** [comment]
I think our examples are good now, or will be once #126 is fixed.
