### ISSUE TITLE
Get functionality of catalog_util into TDSCatalog

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/siphon#4]
Make sure TDSCatalog covers the functionality of catalog_util. This may already be done.

**Comment by dopplershift** [comment]
Do you have a handle on what remains here?

**Comment by lesserwhirls** [comment]
Everything that was in catalog_util is covered. The question is, do we want to make a wrapper function for:

`get_latest_dods_url(catalog_url)`

Currently, this is the same as:

`get_latest_access_url(catalog_url, "OPENDAP")`

**Comment by lesserwhirls** [comment]
Ok, all functionality there, so we're good without wrapping get_latest_access_url to keep method get_latest_dods_url
