### ISSUE TITLE
Timeline for v0.4.0 release and pypi upload?

### ISSUE THREAD

**Issue by jclark754** [Unidata/siphon#42]
I noticed when trying to work with the radarserver class that I was unable to retrieve metadata because I believe this was added right after 0.3.0 release (06/17 if I recall). I was able to resolve this of course by cloning the repo...just wondering in case there are radarserver examples for the workshop and users try to pip install or conda install. Also curious about what features you're considering for the v0.4.0 milestone.

**Comment by dopplershift** [comment]
No 0.4.0 milestone, but there is a milestone for the workshop. I think it will end up being 0.4.0, but I'd rather the version take care of itself (bugfix, features, etc.) based on what we actually get done for a milestone.

Current feature *plans* are whatever is tagged with that milestone, which isn't much in the way of features now. I *would* like to get some of the items discussed in #26 into the next release.

**Comment by jclark754** [comment]
I'll close this since you fixed the `radarserver.metadata` issues with the workshop release and my questions have been resolved.
