### ISSUE TITLE
Requesting a new release

### ISSUE THREAD

**Issue by maresb** [Unidata/siphon#750]
I ran into #317 which was closed two years ago in #478. Perplexed by why my installed version was so old, I was surprised to see that the last release was March 7th 2021, so the fix I want was never released.

Any chance of cutting a Siphon 0.10 release? Thanks!

**Comment by dopplershift** [comment]
We definitely need to get Siphon some love here, including fixing up CI and a new release with a handful of fixes. Trying to get a new release of MetPy out the door, but I'm hoping to get a few hours to tend here after that.

**Comment by dopplershift** [comment]
We're working right now on getting everything up to snuff and putting out a new release as soon as we can.

**Comment by dopplershift** [comment]
0.10.0 is out! Way too overdue, but it's here!

**Comment by Schamschula** [comment]
Thanks!

I just updated the MacPorts Portfile: https://github.com/macports/macports-ports/commit/1b5da938ff2bca579c8c4a7018aca4916d3d75de
