### ISSUE TITLE
TDSCatalog misses the last months entry

### ISSUE THREAD

**Issue by jm-cook** [Unidata/siphon#753]
We are using Siphon 0.9 to access .nc files from an opendap server and see that the last file in a catalog is missing.

Example:

    cat_url = 'https://opendap1-test.nodc.no/opendap/hyrax/DSG/Physics/project/SmartOcean/Austevoll-Sor/catalog.xml'
    cat = TDSCatalog(cat_url)
    print(cat.datasets)

The result is:

    ['NMDC_AR_MO_Austevoll-Sor_202205.nc', 'NMDC_AR_MO_Austevoll-Sor_202206.nc', 'NMDC_AR_MO_Austevoll-Sor_202207.nc', 
    'NMDC_AR_MO_Austevoll-Sor_202208.nc', 'NMDC_AR_MO_Austevoll-Sor_202209.nc', 'NMDC_AR_MO_Austevoll-Sor_202210.nc', 
    'NMDC_AR_MO_Austevoll-Sor_202211.nc', 'NMDC_AR_MO_Austevoll-Sor_202212.nc', 'NMDC_AR_MO_Austevoll-Sor_202301.nc', 
    'NMDC_AR_MO_Austevoll-Sor_202302.nc', 'NMDC_AR_MO_Austevoll-Sor_202303.nc', 'NMDC_AR_MO_Austevoll-Sor_202304.nc', 
    'NMDC_AR_MO_Austevoll-Sor_202306.nc', 'NMDC_AR_MO_Austevoll-Sor_202307.nc', 'NMDC_AR_MO_Austevoll-Sor_202308.nc', 
    'NMDC_AR_MO_Austevoll-Sor_202309.nc', 'NMDC_AR_MO_Austevoll-Sor_202310.nc']

The final entry ``NMDC_AR_MO_Austevoll-Sor_202311.nc`` is missing

The XML for the catalog contains this entry:

    <thredds:dataset name="NMDC_AR_MO_Austevoll-Sor_202311.nc" ID="/opendap/hyrax/DSG/Physics/project/SmartOcean/Austevoll-Sor/NMDC_AR_MO_Austevoll-Sor_202311.nc">
    <thredds:dataSize units="bytes">1005771</thredds:dataSize>
    <thredds:date type="modified">2023-12-05T08:16:28</thredds:date>
    <thredds:access serviceName="dap" urlPath="/DSG/Physics/project/SmartOcean/Austevoll-Sor/NMDC_AR_MO_Austevoll-Sor_202311.nc"/>
    <thredds:access serviceName="file" urlPath="/DSG/Physics/project/SmartOcean/Austevoll-Sor/NMDC_AR_MO_Austevoll-Sor_202311.nc"/>
    </thredds:dataset>

This particular code is running on windows.

    $ python --version                 
    Python 3.11.5
    $ python -c 'import siphon; print(siphon.__version__)'
    0.9

**Comment by jm-cook** [comment]
See also #309

**Comment by dopplershift** [comment]
Thanks for the report. Closing this as a duplicate and leaving #309 to track.
