### ISSUE TITLE
Use OrderedDict in catalogs

### ISSUE THREAD

**Issue by dopplershift** [Unidata/siphon#80]
Right now, all key-value stores within `TDSCatalog` are just plain Python `dict`s. It would be better to use `OrderedDict`, so that the order of iteration matches the order we parse in. That, in theory, would eliminate the need sometimes to sort on date/time to get things in proper order, since the server usually puts the most recent first.

**Comment by lesserwhirls** [comment]
Sounds good to me. I'll take a look after a bit and see how it goes.
