### ISSUE TITLE
Remove unused import

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/siphon#82]
Remove unused netcdf4 import from cdmremote example 

https://github.com/Unidata/siphon/blob/f7f2d6a7cf645e4c652c165f65e20b92ec1dd3d4/examples/notebooks/cdmr/Basic%20CDMRemote%20Demo.ipynb

**Comment by dopplershift** [comment]
Removed this notebook as part of cruft in 7ac2f7cb15bbf0e0bcb0f61a3888c0216c0c2ffc.
