### ISSUE TITLE
Add __str__ methods

### ISSUE THREAD

**Issue by dopplershift** [Unidata/siphon#87]
Having `__str__` methods on classes like `TDSCatalog` and `Dataset` would make it much easier to explore data; it would be especially helpful in teaching contexts.

**Comment by justin1dennison** [comment]
@dopplershift I would like to give this issue a try. What information would be helpful in the `__str__` method output? Are there classes other than `Dataset` and `TDSCatalog` that would be included in these changes?

**Comment by dopplershift** [comment]
That's a really good question...

**Comment by dopplershift** [comment]
So it looks like this was added in #166, and we missed closing this issue. Sorry about that.

Thanks for your interest and feel free to look at our issues marked "good first issue" if you're interested in contributing!
